"""Reports domain ORM models: business-ready reports and their PDF exports.

Both tables are tenant-owned (``org_id NOT NULL``) and protected by forced Row-Level Security
created in migration 0008 (CLAUDE.md §4). Reports and exports are asynchronously generated by
ARQ workers with the Phase-1 worker discipline: an explicit status lifecycle, compare-and-set
claims (``claimed_at`` + ``status``), bounded retry (``attempt_count``), a sweeper for orphaned
work, and a user-visible terminal state (READY or FAILED + reason). Report ``content`` is
structured sections with validated citations; ``generation_metadata`` records the model, prompt
version, generated_at, and source_document_ids for provenance.
"""

from datetime import datetime
from enum import StrEnum
from typing import Any
from uuid import UUID, uuid4

from sqlalchemy import (
    DateTime,
    Enum,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from src.shared.database import Base

REPORT_TYPE_ENUM_NAME = "report_type"
REPORT_STATUS_ENUM_NAME = "report_status"
EXPORT_FORMAT_ENUM_NAME = "export_format"
EXPORT_STATUS_ENUM_NAME = "export_status"


class ReportType(StrEnum):
    EXECUTIVE_SUMMARY = "executive_summary"
    TECHNICAL = "technical"
    RECOMMENDATION = "recommendation"


class ReportStatus(StrEnum):
    QUEUED = "queued"
    GENERATING = "generating"
    READY = "ready"
    FAILED = "failed"


class ExportFormat(StrEnum):
    PDF = "pdf"


class ExportStatus(StrEnum):
    QUEUED = "queued"
    GENERATING = "generating"
    READY = "ready"
    FAILED = "failed"


def _report_type() -> Enum:
    return Enum(
        ReportType, name=REPORT_TYPE_ENUM_NAME, values_callable=lambda e: [m.value for m in e]
    )


def _report_status() -> Enum:
    return Enum(
        ReportStatus, name=REPORT_STATUS_ENUM_NAME, values_callable=lambda e: [m.value for m in e]
    )


def _export_format() -> Enum:
    return Enum(
        ExportFormat, name=EXPORT_FORMAT_ENUM_NAME, values_callable=lambda e: [m.value for m in e]
    )


def _export_status() -> Enum:
    return Enum(
        ExportStatus, name=EXPORT_STATUS_ENUM_NAME, values_callable=lambda e: [m.value for m in e]
    )


class Report(Base):
    """A generated report. Lifecycle queued → generating → ready | failed (Task 6)."""

    __tablename__ = "reports"
    __table_args__ = (
        Index("ix_reports_org_creator_created", "org_id", "created_by", "created_at"),
        # Serves the sweeper scan for orphaned in-flight work (status + claim age).
        Index("ix_reports_status_claimed", "status", "claimed_at"),
    )

    id: Mapped[UUID] = mapped_column(primary_key=True, default=uuid4)
    org_id: Mapped[UUID] = mapped_column(ForeignKey("organizations.id", ondelete="CASCADE"))
    created_by: Mapped[UUID] = mapped_column(ForeignKey("users.id", ondelete="CASCADE"))
    report_type: Mapped[ReportType] = mapped_column(_report_type())
    title: Mapped[str] = mapped_column(String(255))
    source_query: Mapped[str] = mapped_column(Text)
    collection_scope: Mapped[list[str]] = mapped_column(JSONB, default=list)
    status: Mapped[ReportStatus] = mapped_column(_report_status())
    failure_reason: Mapped[str | None] = mapped_column(String(128), nullable=True)
    # Structured sections + citations (ReportContent) when ready; null until then.
    content: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    # model, prompt_version, generated_at, source_document_ids.
    generation_metadata: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    attempt_count: Mapped[int] = mapped_column(Integer, default=0)
    claimed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    trace_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )


class ReportExport(Base):
    """One export of a report in a given format. Idempotent per (report_id, format)."""

    __tablename__ = "report_exports"
    __table_args__ = (
        UniqueConstraint("report_id", "format", name="uq_report_exports_report_id_format"),
        Index("ix_report_exports_status_claimed", "status", "claimed_at"),
    )

    id: Mapped[UUID] = mapped_column(primary_key=True, default=uuid4)
    org_id: Mapped[UUID] = mapped_column(ForeignKey("organizations.id", ondelete="CASCADE"))
    report_id: Mapped[UUID] = mapped_column(ForeignKey("reports.id", ondelete="CASCADE"))
    format: Mapped[ExportFormat] = mapped_column(_export_format())
    status: Mapped[ExportStatus] = mapped_column(_export_status())
    storage_key: Mapped[str | None] = mapped_column(String(512), nullable=True)
    failure_reason: Mapped[str | None] = mapped_column(String(128), nullable=True)
    attempt_count: Mapped[int] = mapped_column(Integer, default=0)
    claimed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
