"""Deterministic, dependency-free PDF rendering for report exports (ADR 0018: fpdf2, no
system/browser deps). A pure function ``render_report_pdf(content) -> bytes`` — the structured
report content + metadata are the inputs, so a swept re-export is content-identical. Citations
render as a numbered Sources list (endnotes) keyed by the same inline ``[n]`` markers; every
page carries a generation-metadata footer (model · prompt version · generated_at)."""

from datetime import UTC, datetime
from typing import Any

from fpdf import FPDF
from fpdf.enums import XPos, YPos

_FONT = "Helvetica"
# A fixed PDF creation date so the rendered bytes are deterministic (a swept re-export of the
# same report content is byte-identical). The report's own generated_at lives in the footer.
_FIXED_CREATION_DATE = datetime(2020, 1, 1, tzinfo=UTC)


class _ReportPDF(FPDF):
    def __init__(self, footer_text: str) -> None:
        super().__init__()
        self._footer_text = footer_text
        self.set_auto_page_break(auto=True, margin=20)

    def footer(self) -> None:  # fpdf2 calls this on every page
        self.set_y(-15)
        self.set_font(_FONT, "I", 8)
        self.set_text_color(120, 120, 120)
        self.cell(0, 10, self._footer_text, align="C")
        self.set_text_color(0, 0, 0)


def _source_label(citation: dict[str, Any]) -> str:
    page = citation.get("page_ref")
    return f"{citation['filename']}, p.{page}" if page is not None else str(citation["filename"])


def render_report_pdf(
    *,
    title: str,
    sections: list[dict[str, Any]],
    citations: list[dict[str, Any]],
    metadata: dict[str, Any],
) -> bytes:
    """Render a report to PDF bytes. Time: O(report length). Space: O(report length)."""
    footer = (
        f"Generated by {metadata.get('model', 'unknown')} · "
        f"prompt {metadata.get('prompt_version', '?')} · {metadata.get('generated_at', '')}"
    )
    pdf = _ReportPDF(footer)
    pdf.set_creation_date(_FIXED_CREATION_DATE)  # deterministic bytes
    pdf.add_page()

    def line(height: float, text: str) -> None:
        pdf.multi_cell(0, height, text, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_font(_FONT, "B", 18)
    line(10, title)
    pdf.ln(4)

    for section in sections:
        pdf.set_font(_FONT, "B", 13)
        line(8, str(section["heading"]))
        pdf.set_font(_FONT, size=11)
        markers = "".join(f" [{n}]" for n in section.get("citation_markers", []))
        line(6, f"{section['body']}{markers}")
        pdf.ln(3)

    if citations:
        pdf.ln(2)
        pdf.set_font(_FONT, "B", 13)
        line(8, "Sources")
        pdf.set_font(_FONT, size=10)
        for citation in sorted(citations, key=lambda c: c["marker_index"]):
            line(6, f"[{citation['marker_index']}] {_source_label(citation)}")

    return bytes(pdf.output())
